### PR TITLE
Use docker image of busybox with glibc libraries.

### PR DESCRIPTION
**Pull request by looked-at-me**

### CODE REVIEW

**Comment by Geod24** [comment]
What's the issue ?

**Comment by looked-at-me** [comment]
The dlang-tour executable uses glibc, but busybox doesn't have it unless you specifically ask for it (which this patch does). It fixes the shorten link button, essentially.

Also the build error is caused by a change in one of the libraries used in the example source codes.

Here: https://github.com/dlang-tour/mir/pull/5

**Comment by Geod24** [comment]
Thanks for taking care of this! Looks like the PR you linked also triggers one of the Vibe.d regression we've been seeing recently... Waiting for upstream to merge it.

**Comment by looked-at-me** [comment]
Well the LDC build that makes the docker image is passing. The other DMD fails seem to be related to that vibe.d regression.

**Comment by wilzbach** [comment]
Let's just see what happens when deployed. Thank you very much!

**Comment by looked-at-me** [comment]
Well the shorten buttons work as well as Gist (is a bit slow), but the link for gist gives 502 bad gateway.

**Pull request merged**
