### PR TITLE
update dyaml to 0.7.1

### PR DESCRIPTION
**Pull request by BBasile**
Needed for the D project tester to pass, specifically https://github.com/dlang/phobos/pull/6790.

### CODE REVIEW

**Comment by BBasile** [comment]
You'll need to push a tag too.

**Comment by wilzbach** [comment]
Tagged as v1.1.1

**Comment by BBasile** [comment]
the DEPLOY build failure was not a problem ?

**Comment by joakim-noah** [comment]
Now it says it can't find the English submodule commit, breaking buildkite.

**Pull request merged**
